import type { ProductRecord } from "@/types/database";

export const demoProducts: ProductRecord[] = [
  {
    id: "demo-1",
    created_at: "2026-05-01T10:00:00.000Z",
    updated_at: "2026-05-01T10:00:00.000Z",
    name: "Pink Heart Jeans",
    slug: "pink-heart-jeans",
    category: "Jeans",
    price: 180,
    size: "38",
    size_system: "EU",
    status: "available",
    short_description:
      "Bubblegum pink jeans with heart patching and soft Y2K attitude.",
    full_description:
      "Upcycled pink denim reworked by hand with tonal heart appliques, soft distressing and a low-key sugary finish. A playful anti-basic piece built for a full look or a pop contrast styling.",
    main_image_url: "/brand/products/jean-bonbon-rose/front.png",
    gallery_image_urls: [
      "/brand/products/jean-bonbon-rose/front.png",
      "/brand/products/jean-bonbon-rose/detail.png",
    ],
    featured: true,
    is_unique_piece: true,
    materials: "Upcycled denim, applique patches, lace detail.",
    techniques: ["upcycling", "patchwork", "sewing"],
    collection_name: "Bubble Threat",
    drop_date: "2026-05-01",
    instagram_post_url: null,
    sort_order: 1,
  },
  {
    id: "demo-2",
    created_at: "2026-05-01T11:00:00.000Z",
    updated_at: "2026-05-01T11:00:00.000Z",
    name: "Silver Micro Skirt",
    slug: "silver-micro-skirt",
    category: "Skirts",
    price: 145,
    size: "36",
    size_system: "EU",
    status: "available",
    short_description:
      "Metallic pleated mini skirt with futurist brat energy.",
    full_description:
      "Reflective silver mini with pleated hem and side tie, cut to feel like a cyber-pop schoolgirl artifact. Sharp, shiny and deliberately loud under flash or nightlife lighting.",
    main_image_url: "/brand/products/minijupe-argente/front.png",
    gallery_image_urls: [
      "/brand/products/minijupe-argente/front.png",
      "/brand/products/minijupe-argente/back.png",
    ],
    featured: true,
    is_unique_piece: true,
    materials: "Metallic-coated fabric, reworked construction.",
    techniques: ["sewing", "reconstruction"],
    collection_name: "Chrome Doll",
    drop_date: "2026-05-01",
    instagram_post_url: null,
    sort_order: 2,
  },
  {
    id: "demo-3",
    created_at: "2026-05-01T12:00:00.000Z",
    updated_at: "2026-05-01T12:00:00.000Z",
    name: "Snake Mesh Corset",
    slug: "snake-mesh-corset",
    category: "Tops",
    price: 170,
    size: "S / M",
    size_system: "INT",
    status: "reserved",
    short_description:
      "Laced corset top with pale pink mesh and reptile ghost print.",
    full_description:
      "Handmade corset mixing lace-up structure, pale pink mesh inserts and printed textile fragments. Built as a one-of-one top that sits between lingerie, clubwear and reworked artefact.",
    main_image_url: "/brand/products/corset-snake/front.png",
    gallery_image_urls: [
      "/brand/products/corset-snake/front.png",
      "/brand/products/corset-snake/detail.png",
    ],
    featured: true,
    is_unique_piece: true,
    materials: "Reclaimed textile, mesh, eyelets, ribbon lacing.",
    techniques: ["corsetry", "upcycling", "sewing"],
    collection_name: "Soft Venom",
    drop_date: "2026-05-01",
    instagram_post_url: null,
    sort_order: 3,
  },
  {
    id: "demo-4",
    created_at: "2026-05-01T13:00:00.000Z",
    updated_at: "2026-05-01T13:00:00.000Z",
    name: "Denim Lace Corset Halter",
    slug: "denim-lace-corset-halter",
    category: "Tops",
    price: 155,
    size: "S",
    size_system: "INT",
    status: "available",
    short_description:
      "Light-wash denim halter with lace trim and tied front.",
    full_description:
      "A reconstructed denim halter top trimmed with delicate lace and corset lacing, shaped to flirt with early-2000s mall-girl nostalgia and underground DIY styling at once.",
    main_image_url: "/brand/products/haut-jean-corset/front.png",
    gallery_image_urls: [
      "/brand/products/haut-jean-corset/front.png",
      "/brand/products/haut-jean-corset/detail.png",
    ],
    featured: false,
    is_unique_piece: true,
    materials: "Upcycled denim, lace trim, metal eyelets.",
    techniques: ["reconstruction", "lace", "sewing"],
    collection_name: "Denim Angel",
    drop_date: "2026-05-01",
    instagram_post_url: null,
    sort_order: 4,
  },
  {
    id: "demo-5",
    created_at: "2026-05-01T14:00:00.000Z",
    updated_at: "2026-05-01T14:00:00.000Z",
    name: "Pink Twin Set",
    slug: "pink-twin-set",
    category: "Custom pieces",
    price: 260,
    size: "S / M",
    size_system: "INT",
    status: "available",
    short_description:
      "Candy-pink set built as a full look for a maximal Y2K silhouette.",
    full_description:
      "A coordinated reworked look in washed pink tones, styled as a statement set rather than a neutral basic. Romantic details and brat energy meet in a deliberately visible handmade finish.",
    main_image_url: "/brand/products/ensemble-rose/look-1.png",
    gallery_image_urls: [
      "/brand/products/ensemble-rose/look-1.png",
      "/brand/products/ensemble-rose/look-2.png",
    ],
    featured: true,
    is_unique_piece: true,
    materials: "Upcycled fabric mix, re-cut details, handmade finishing.",
    techniques: ["custom set", "sewing", "reconstruction"],
    collection_name: "Bubble Threat",
    drop_date: "2026-05-01",
    instagram_post_url: null,
    sort_order: 5,
  },
];
